# -*- coding: utf-8 -*-
"""bubble_sort_f.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-asMsjgUaKVeRbXJRgmSI_Y-BD016YNO
"""

import os
import sys
from datetime import datetime
import tkinter as tk
from tkinter import filedialog

def bubble_sort_files(files, sort_by):
    n = len(files)
    for i in range(n):
        for j in range(0, n-i-1):
            if sort_by == "size":
                if os.path.getsize(files[j]) > os.path.getsize(files[j+1]):
                    files[j], files[j+1] = files[j+1], files[j]
            elif sort_by == "date":
                if os.path.getctime(files[j]) > os.path.getctime(files[j+1]):
                    files[j], files[j+1] = files[j+1], files[j]
def list_files_in_directory():
    directory = directory_var.get()
    if not os.path.isdir(directory):
        result_var.set("Invalid directory.")
        return

    files = list_files(directory)
    result_listbox.delete(0, tk.END)
    for file in files:
        result_listbox.insert(tk.END, file)

def create_new_directory():
    directory = directory_var.get()
    new_directory = os.path.join(directory, "New Folder")
    create_directory(new_directory)

def create_new_file():
    directory = directory_var.get()
    new_file = os.path.join(directory, "New File.txt")
    create_file(new_file)

def delete_selected_file():
    selected_file = result_listbox.get(result_listbox.curselection())
    delete_file(selected_file)
    result_listbox.delete(result_listbox.curselection())



def browse_directory():
    directory = filedialog.askdirectory()
    directory_var.set(directory)

def sort_files():
    directory = directory_var.get()
    sort_by = sort_by_var.get()

    if not os.path.isdir(directory):
        result_var.set("Invalid directory.")
        return

    files = [os.path.join(directory, f) for f in os.listdir(directory) if os.path.isfile(os.path.join(directory, f))]
    bubble_sort_files(files, sort_by)

    result_listbox.delete(0, tk.END)
    for file in files:
        result_listbox.insert(tk.END, file)

app = tk.Tk()
app.title("Bubble Sort Files")


directory_var = tk.StringVar()
sort_by_var = tk.StringVar()

frame1 = tk.Frame(app)
frame1.pack(padx=10, pady=10)

frame2 = tk.Frame(app)
frame2.pack(padx=10, pady=10)

frame3 = tk.Frame(app)
frame3.pack(padx=10, pady=10)

frame4 = tk.Frame(app)
frame4.pack(padx=10, pady=10)

button3 = tk.Button(frame4, text="List Files", command=list_files_in_directory)
button3.pack(side=tk.LEFT)

button4 = tk.Button(frame4, text="Create Directory", command=create_new_directory)
button4.pack(side=tk.LEFT)

button5 = tk.Button(frame4, text="Create File", command=create_new_file)
button5.pack(side=tk.LEFT)

button6 = tk.Button(frame4, text="Delete", command=delete_selected_file)
button6.pack(side=tk.LEFT)

label1 = tk.Label(frame1, text="Directory:")
label1.pack(side=tk.LEFT)

entry1 = tk.Entry(frame1, textvariable=directory_var, width=40)
entry1.pack(side=tk.LEFT)

button1 = tk.Button(frame1, text="Browse", command=browse_directory)
button1.pack(side=tk.LEFT)

label2 = tk.Label(frame2, text="Sort by:")
label2.pack(side=tk.LEFT)

option_menu = tk.OptionMenu(frame2, sort_by_var, "size", "date")
sort_by_var.set("size")
option_menu.pack(side=tk.LEFT)

button2 = tk.Button(frame2, text="Sort", command=sort_files)
button2.pack(side=tk.LEFT)

result_listbox = tk.Listbox(frame3, width=60, height=20)
result_listbox.pack()

app.mainloop()

